[package]
name = "base-n-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.19.2"

[profile.release]
lto = "fat"
codegen-units = 1
